# Generated by Django 2.2.9 on 2020-09-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='group_posts', to='posts.Group'),
        ),
    ]
